version: "3.8"
services:

  first_app:
    build: .
    ports:
      - 3131:3131
    volumes:
      - ./metrics.js:/app/metrics.js

  second_app:
    build: .
    ports:
      - 3232:3131
    volumes:
      - ./metrics.js:/app/metrics.js

  prometheus:
    image: prom/prometheus
    depends_on:
      - first_app
      - second_app
    ports:
      - 9090:9090
    volumes:
      - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

  # node_exporter:
  #   image: bitnami/node-exporter
  #   ports:
  #     - 9100:9100
