global:
  scrape_interval:     10s
  evaluation_interval: 30s

scrape_configs:
- job_name: node_exporter
  static_configs:
  - targets: ['node_exporter:9100']

- job_name: node_app
  static_configs:
  - targets: ['app:3131']
