global:
  scrape_interval:     10s
  evaluation_interval: 30s

scrape_configs:
- job_name: node_app
  static_configs:
  - targets: ['first_app:3131', 'second_app:3131']

# - job_name: prometheus
#   static_configs:
#   - targets: ['localhost:9090']

# - job_name: node_exporter
#   static_configs:
#   - targets: ['node_exporter:9100']
